[build]
  publish = "frontend/dist"
  command = "npm run build"

[[functions]]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[functions]]
  # Run scheduled-fetch.js every Sunday at midnight UTC
  name = "scheduled-fetch"
  schedule = "0 0 * * 0"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200